import PropTypes from 'prop-types';
import { Sparkles } from 'lucide-react';

function AIBadge({ isAIGenerated = false, className = '', size = 'small' }) {
  if (!isAIGenerated) return null;

  const sizeClasses = {
    small: 'text-xs px-2 py-1',
    medium: 'text-sm px-3 py-1.5'
  };

  return (
    <span
      className={`
        inline-flex items-center 
        bg-blue-500 text-white 
        rounded-full
        ${sizeClasses[size]} 
        ${className}
      `}
    >
      <Sparkles size={12} style={{ color: '#00D9FF' }} />
      <span className="font-semibold" style={{ color: '#00D9FF' }}>
        AI Generated
      </span>
    </span>
  );
}

AIBadge.propTypes = {
  /** Whether the content was generated by AI */
  isAIGenerated: PropTypes.bool,
  /** Additional CSS classes to apply to the badge */
  className: PropTypes.string,
  /** Size variant of the badge */
  size: PropTypes.oneOf(['small', 'medium'])
};

export default AIBadge;
<AIBadge isAIGenerated={true} className="ml-2" />